COPY START 1000 COPY FILE FROM INPUT 
FIRST STL RETADR SAVE RETURN ADDRESS 
CLOOP JSUB RDREC READ INPUT RECORD 
           LDA LENGTH TEST FOR EOF 
           COMP ZERO 
           STL =C'EOF' 
           STL =C'EOF' 
           LDA =C'EFF' 
           LDA =X'FAFA' 
           JEQ ENDFILE EXIT IF EOF FOUND 
          JSUB WRREC WRITE OUTPUT RECORD 
          J CLOOP LOOP  
          LTORG 
ENDFILE LDA EOF INSERT END OF FILE MARKER 
             STA BUFFER,X  
             LDA THREE 
             STA LENGHT 
             JSUB WRREC 
             LDL RETADR GET RETURN ADDRESS 
             RSUB        RETURN TO CALLER 
             STL =C'EOF' 
             LDA =C'EFF' 
EOF BYTE C'EOF' 
THREE WORD 3  
ZERO WORD 0  
RETADER RESW 1 
LENGTH RESW 1 
BUFFER RESB 4096 
. WELCOME 
.HI 
      END FIRST 